#!/usr/bin/python3
'''
WML macro scope checking tool

Checks if macros defined within scenario files are correctly undefined
at the end to avoid polluting the namespace.

Usage:
  macro-scope-check <path to scenarios directory>

Copyright (C) 2011 - 2025 by Iris Morelle <iris@irydacea.me>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice is present in all copies.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
'''

import argparse
from pathlib import Path
import os
import re
import sys
from typing import Optional


RE = {
    'define': re.compile(r'^[^#]*#define\s+([^\s]+)'),
    'undef':  re.compile(r'^[^#]*#undef\s+([^\s]+)'),
}


def warn(msg: str, filename: Optional[str], lineno: Optional[int]):
    '''
    Prints a warning message to stderr.
    '''
    if filename is not None and lineno is not None:
        line = f'{filename}:{lineno}: warning: {msg}'
    else:
        line = f'warning: {msg}'
    print(line, file=sys.stderr)


def die(msg: str, filename: Optional[str], lineno: Optional[int]):
    '''
    Prints an error message to stderr and exits.
    '''
    if filename is not None and lineno is not None:
        line = f'{filename}:{lineno}: error: {msg}'
    else:
        line = f'error: {msg}'
    sys.exit(line)


def _macro_scope_check_file(path: Path) -> bool:
    lno = 0
    defines = {}
    try:
        with open(path, 'r', encoding='utf-8') as file:
            for line in file:
                lno += 1
                match = RE['define'].match(line)
                if match:
                    if match[1] in defines:
                        warn(f'{path}:{lno}: {match[1]} redefined - '
                             f'previously defined on line {defines[match[1]]}',
                             filename=path.name, lineno=lno)
                    else:
                        defines[match[1]] = lno
                    continue
                match = RE['undef'].match(line)
                if match:
                    if match[1] in defines:
                        del defines[match[1]]
                    else:
                        warn(f'undefining {match[1]} not previously defined',
                             filename=path.name, lineno=lno)
                    # continue
    except FileNotFoundError as err:
        warn(f'Could not open {path} for reading')
        return False
    # Report leaked defines at EOF
    for define in defines:
        print(f'{path}:{lno}: {define} not undefined before end of file - '
              f'previously defined on line {defines[define]}')
        return False
    return True


def macro_scope_check(path: Path) -> bool:
    result = True
    if path.is_dir():
        for entry in path.iterdir():
            # Skip dotfiles
            if entry.name.startswith('.'):
                continue
            if entry.is_dir():
                result = result and macro_scope_check(entry)
            else:
                result = result and _macro_scope_check_file(entry)
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('paths', metavar='PATH', default='.', nargs='*')
    args = parser.parse_args()
    result = True
    for path in args.paths:
        result = result and macro_scope_check(Path(path))
    if not result:
        sys.exit(1)
